<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class provinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data=[
            ['ubigeo'=>'0101', 'nombre'=>'Chachapoyas', 'departamento_id'=>'01','status'=>1],
            ['ubigeo'=>'0102', 'nombre'=>'Bagua', 'departamento_id'=>'01','status'=>1],
            ['ubigeo'=>'0103', 'nombre'=>'Bongará', 'departamento_id'=>'01','status'=>1],
            ['ubigeo'=>'0104', 'nombre'=>'Condorcanqui', 'departamento_id'=>'01','status'=>1],
            ['ubigeo'=>'0105', 'nombre'=>'Luya', 'departamento_id'=>'01','status'=>1],
            ['ubigeo'=>'0106', 'nombre'=>'Rodríguez de Mendoza', 'departamento_id'=>'01','status'=>1],
            ['ubigeo'=>'0107', 'nombre'=>'Utcubamba', 'departamento_id'=>'01','status'=>1],
            ['ubigeo'=>'0201', 'nombre'=>'Huaraz', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0202', 'nombre'=>'Aija', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0203', 'nombre'=>'Antonio Raymondi', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0204', 'nombre'=>'Asunción', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0205', 'nombre'=>'Bolognesi', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0206', 'nombre'=>'Carhuaz', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0207', 'nombre'=>'Carlos Fermín Fitzcarrald', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0208', 'nombre'=>'Casma', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0209', 'nombre'=>'Corongo', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0210', 'nombre'=>'Huari', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0211', 'nombre'=>'Huarmey', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0212', 'nombre'=>'Huaylas', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0213', 'nombre'=>'Mariscal Luzuriaga', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0214', 'nombre'=>'Ocros', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0215', 'nombre'=>'Pallasca', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0216', 'nombre'=>'Pomabamba', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0217', 'nombre'=>'Recuay', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0218', 'nombre'=>'Santa', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0219', 'nombre'=>'Sihuas', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0220', 'nombre'=>'Yungay', 'departamento_id'=>'02','status'=>1],
            ['ubigeo'=>'0301', 'nombre'=>'Abancay', 'departamento_id'=>'03','status'=>1],
            ['ubigeo'=>'0302', 'nombre'=>'Andahuaylas', 'departamento_id'=>'03','status'=>1],
            ['ubigeo'=>'0303', 'nombre'=>'Antabamba', 'departamento_id'=>'03','status'=>1],
            ['ubigeo'=>'0304', 'nombre'=>'Aymaraes', 'departamento_id'=>'03','status'=>1],
            ['ubigeo'=>'0305', 'nombre'=>'Cotabambas', 'departamento_id'=>'03','status'=>1],
            ['ubigeo'=>'0306', 'nombre'=>'Chincheros', 'departamento_id'=>'03','status'=>1],
            ['ubigeo'=>'0307', 'nombre'=>'Grau', 'departamento_id'=>'03','status'=>1],
            ['ubigeo'=>'0401', 'nombre'=>'Arequipa', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0402', 'nombre'=>'Camaná', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0403', 'nombre'=>'Caravelí', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0404', 'nombre'=>'Castilla', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0405', 'nombre'=>'Caylloma', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0406', 'nombre'=>'Condesuyos', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0407', 'nombre'=>'Islay', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0408', 'nombre'=>'La Uniòn', 'departamento_id'=>'04','status'=>1],
            ['ubigeo'=>'0501', 'nombre'=>'Huamanga', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0502', 'nombre'=>'Cangallo', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0503', 'nombre'=>'Huanca Sancos', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0504', 'nombre'=>'Huanta', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0505', 'nombre'=>'La Mar', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0506', 'nombre'=>'Lucanas', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0507', 'nombre'=>'Parinacochas', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0508', 'nombre'=>'Pàucar del Sara Sara', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0509', 'nombre'=>'Sucre', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0510', 'nombre'=>'Víctor Fajardo', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0511', 'nombre'=>'Vilcas Huamán', 'departamento_id'=>'05','status'=>1],
            ['ubigeo'=>'0601', 'nombre'=>'Cajamarca', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0602', 'nombre'=>'Cajabamba', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0603', 'nombre'=>'Celendín', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0604', 'nombre'=>'Chota', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0605', 'nombre'=>'Contumazá', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0606', 'nombre'=>'Cutervo', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0607', 'nombre'=>'Hualgayoc', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0608', 'nombre'=>'Jaén', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0609', 'nombre'=>'San Ignacio', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0610', 'nombre'=>'San Marcos', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0611', 'nombre'=>'San Miguel', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0612', 'nombre'=>'San Pablo', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0613', 'nombre'=>'Santa Cruz', 'departamento_id'=>'06','status'=>1],
            ['ubigeo'=>'0701', 'nombre'=>'Prov. Const. del Callao', 'departamento_id'=>'07','status'=>1],
            ['ubigeo'=>'0801', 'nombre'=>'Cusco', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0802', 'nombre'=>'Acomayo', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0803', 'nombre'=>'Anta', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0804', 'nombre'=>'Calca', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0805', 'nombre'=>'Canas', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0806', 'nombre'=>'Canchis', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0807', 'nombre'=>'Chumbivilcas', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0808', 'nombre'=>'Espinar', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0809', 'nombre'=>'La Convención', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0810', 'nombre'=>'Paruro', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0811', 'nombre'=>'Paucartambo', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0812', 'nombre'=>'Quispicanchi', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0813', 'nombre'=>'Urubamba', 'departamento_id'=>'08','status'=>1],
            ['ubigeo'=>'0901', 'nombre'=>'Huancavelica', 'departamento_id'=>'09','status'=>1],
            ['ubigeo'=>'0902', 'nombre'=>'Acobamba', 'departamento_id'=>'09','status'=>1],
            ['ubigeo'=>'0903', 'nombre'=>'Angaraes', 'departamento_id'=>'09','status'=>1],
            ['ubigeo'=>'0904', 'nombre'=>'Castrovirreyna', 'departamento_id'=>'09','status'=>1],
            ['ubigeo'=>'0905', 'nombre'=>'Churcampa', 'departamento_id'=>'09','status'=>1],
            ['ubigeo'=>'0906', 'nombre'=>'Huaytará', 'departamento_id'=>'09','status'=>1],
            ['ubigeo'=>'0907', 'nombre'=>'Tayacaja', 'departamento_id'=>'09','status'=>1],
            ['ubigeo'=>'1001', 'nombre'=>'Huánuco', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1002', 'nombre'=>'Ambo', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1003', 'nombre'=>'Dos de Mayo', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1004', 'nombre'=>'Huacaybamba', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1005', 'nombre'=>'Huamalíes', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1006', 'nombre'=>'Leoncio Prado', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1007', 'nombre'=>'Marañón', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1008', 'nombre'=>'Pachitea', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1009', 'nombre'=>'Puerto Inca', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1010', 'nombre'=>'Lauricocha ', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1011', 'nombre'=>'Yarowilca ', 'departamento_id'=>'10','status'=>1],
            ['ubigeo'=>'1101', 'nombre'=>'Ica ', 'departamento_id'=>'11','status'=>1],
            ['ubigeo'=>'1102', 'nombre'=>'Chincha ', 'departamento_id'=>'11','status'=>1],
            ['ubigeo'=>'1103', 'nombre'=>'Nasca ', 'departamento_id'=>'11','status'=>1],
            ['ubigeo'=>'1104', 'nombre'=>'Palpa ', 'departamento_id'=>'11','status'=>1],
            ['ubigeo'=>'1105', 'nombre'=>'Pisco ', 'departamento_id'=>'11','status'=>1],
            ['ubigeo'=>'1201', 'nombre'=>'Huancayo ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1202', 'nombre'=>'Concepción ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1203', 'nombre'=>'Chanchamayo ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1204', 'nombre'=>'Jauja ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1205', 'nombre'=>'Junín ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1206', 'nombre'=>'Satipo ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1207', 'nombre'=>'Tarma ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1208', 'nombre'=>'Yauli ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1209', 'nombre'=>'Chupaca ', 'departamento_id'=>'12','status'=>1],
            ['ubigeo'=>'1301', 'nombre'=>'Trujillo ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1302', 'nombre'=>'Ascope ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1303', 'nombre'=>'Bolívar ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1304', 'nombre'=>'Chepén ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1305', 'nombre'=>'Julcán ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1306', 'nombre'=>'Otuzco ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1307', 'nombre'=>'Pacasmayo ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1308', 'nombre'=>'Pataz ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1309', 'nombre'=>'Sánchez Carrión ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1310', 'nombre'=>'Santiago de Chuco ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1311', 'nombre'=>'Gran Chimú ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1312', 'nombre'=>'Virú ', 'departamento_id'=>'13','status'=>1],
            ['ubigeo'=>'1401', 'nombre'=>'Chiclayo ', 'departamento_id'=>'14','status'=>1],
            ['ubigeo'=>'1402', 'nombre'=>'Ferreñafe ', 'departamento_id'=>'14','status'=>1],
            ['ubigeo'=>'1403', 'nombre'=>'Lambayeque ', 'departamento_id'=>'14','status'=>1],
            ['ubigeo'=>'1501', 'nombre'=>'Lima ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1502', 'nombre'=>'Barranca ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1503', 'nombre'=>'Cajatambo ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1504', 'nombre'=>'Canta ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1505', 'nombre'=>'Cañete ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1506', 'nombre'=>'Huaral ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1507', 'nombre'=>'Huarochirí ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1508', 'nombre'=>'Huaura ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1509', 'nombre'=>'Oyón ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1510', 'nombre'=>'Yauyos ', 'departamento_id'=>'15','status'=>1],
            ['ubigeo'=>'1601', 'nombre'=>'Maynas ', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1602', 'nombre'=>'Alto Amazonas ', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1603', 'nombre'=>'Loreto ', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1604', 'nombre'=>'Mariscal Ramón Castilla ', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1605', 'nombre'=>'Requena ', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1606', 'nombre'=>'Ucayali ', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1607', 'nombre'=>'Datem del Marañón ', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1608', 'nombre'=>'Putumayo', 'departamento_id'=>'16','status'=>1],
            ['ubigeo'=>'1701', 'nombre'=>'Tambopata ', 'departamento_id'=>'17','status'=>1],
            ['ubigeo'=>'1702', 'nombre'=>'Manu ', 'departamento_id'=>'17','status'=>1],
            ['ubigeo'=>'1703', 'nombre'=>'Tahuamanu ', 'departamento_id'=>'17','status'=>1],
            ['ubigeo'=>'1801', 'nombre'=>'Mariscal Nieto ', 'departamento_id'=>'18','status'=>1],
            ['ubigeo'=>'1802', 'nombre'=>'General Sánchez Cerro ', 'departamento_id'=>'18','status'=>1],
            ['ubigeo'=>'1803', 'nombre'=>'Ilo ', 'departamento_id'=>'18','status'=>1],
            ['ubigeo'=>'1901', 'nombre'=>'Pasco ', 'departamento_id'=>'19','status'=>1],
            ['ubigeo'=>'1902', 'nombre'=>'Daniel Alcides Carrión ', 'departamento_id'=>'19','status'=>1],
            ['ubigeo'=>'1903', 'nombre'=>'Oxapampa ', 'departamento_id'=>'19','status'=>1],
            ['ubigeo'=>'2001', 'nombre'=>'Piura ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2002', 'nombre'=>'Ayabaca ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2003', 'nombre'=>'Huancabamba ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2004', 'nombre'=>'Morropón ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2005', 'nombre'=>'Paita ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2006', 'nombre'=>'Sullana ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2007', 'nombre'=>'Talara ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2008', 'nombre'=>'Sechura ', 'departamento_id'=>'20','status'=>1],
            ['ubigeo'=>'2101', 'nombre'=>'Puno ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2102', 'nombre'=>'Azángaro ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2103', 'nombre'=>'Carabaya ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2104', 'nombre'=>'Chucuito ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2105', 'nombre'=>'El Collao ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2106', 'nombre'=>'Huancané ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2107', 'nombre'=>'Lampa ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2108', 'nombre'=>'Melgar ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2109', 'nombre'=>'Moho ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2110', 'nombre'=>'San Antonio de Putina ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2111', 'nombre'=>'San Román ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2112', 'nombre'=>'Sandia ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2113', 'nombre'=>'Yunguyo ', 'departamento_id'=>'21','status'=>1],
            ['ubigeo'=>'2201', 'nombre'=>'Moyobamba ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2202', 'nombre'=>'Bellavista ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2203', 'nombre'=>'El Dorado ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2204', 'nombre'=>'Huallaga ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2205', 'nombre'=>'Lamas ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2206', 'nombre'=>'Mariscal Cáceres ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2207', 'nombre'=>'Picota ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2208', 'nombre'=>'Rioja ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2209', 'nombre'=>'San Martín ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2210', 'nombre'=>'Tocache ', 'departamento_id'=>'22','status'=>1],
            ['ubigeo'=>'2301', 'nombre'=>'Tacna ', 'departamento_id'=>'23','status'=>1],
            ['ubigeo'=>'2302', 'nombre'=>'Candarave ', 'departamento_id'=>'23','status'=>1],
            ['ubigeo'=>'2303', 'nombre'=>'Jorge Basadre ', 'departamento_id'=>'23','status'=>1],
            ['ubigeo'=>'2304', 'nombre'=>'Tarata ', 'departamento_id'=>'23','status'=>1],
            ['ubigeo'=>'2401', 'nombre'=>'Tumbes ', 'departamento_id'=>'24','status'=>1],
            ['ubigeo'=>'2402', 'nombre'=>'Contralmirante Villar ', 'departamento_id'=>'24','status'=>1],
            ['ubigeo'=>'2403', 'nombre'=>'Zarumilla ', 'departamento_id'=>'24','status'=>1],
            ['ubigeo'=>'2501', 'nombre'=>'Coronel Portillo ', 'departamento_id'=>'25','status'=>1],
            ['ubigeo'=>'2502', 'nombre'=>'Atalaya ', 'departamento_id'=>'25','status'=>1],
            ['ubigeo'=>'2503', 'nombre'=>'Padre Abad ', 'departamento_id'=>'25','status'=>1],
            ['ubigeo'=>'2504', 'nombre'=>'Purús', 'departamento_id'=>'25','status'=>1]
        ];
        
        \App\Models\Provincia::insert($data);
    }
}
